# Generated by Django 4.2.5 on 2023-10-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalimage',
            old_name='product',
            new_name='name',
        ),
    ]
