# Generated by Django 4.2.5 on 2023-10-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_additionalimage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalimage',
            old_name='name',
            new_name='product',
        ),
    ]
