# Generated by Django 4.2.5 on 2023-10-20 08:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_additionalimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='additional_image',
            field=models.ImageField(upload_to=app.models.image_path_for_add_images),
        ),
    ]
